# See https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html
---
namespace: community
name: esxi
version: 0.1.0
readme: README.md
authors:
  - David Danielsson (github.com/djdanielsson)
  - Alexey Vekshin (github.com/veksh)
description: Collection for working with base VMware ESXi
license_file: LICENSE
tags:
# tags so people can search for collections https://galaxy.ansible.com/search
# tags are all lower-case, no spaces, no dashes.
  - hypervisor
  - ESXi
  - VMware
repository: https://github.com/djdanielsson/ansible-esxi
#documentation: https://github.com/ansible-collection-migration/ansible-esxi/tree/main/docs
homepage: https://github.com/djdanielsson/ansible-esxi
issues: https://github.com/djdanielsson/ansible-esxi/issues
build_ignore:
# https://docs.ansible.com/ansible/devel/dev_guide/developing_collections_distributing.html#ignoring-files-and-folders
  - .gitignore
  - changelogs/.plugin-cache.yaml
...
